; PlatformIO Project Configuration File - R-Sync ESP32 Local Server
; Firmware: https://github.com/Zenalghi/relay-local-server
; Flutter App: https://github.com/Zenalghi/r_sync_app
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
default_envs = esp32doit-devkit-v1
extra_configs = secrets.ini

[env]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
board_build.partitions = min_spiffs.csv
build_flags =
    -DOTA_PASSWORD=\"${secrets.ota_password}\"
lib_deps =
    adafruit/Adafruit GFX Library@^1.12.4
    adafruit/Adafruit SSD1306@^2.5.16
    tzapu/WiFiManager@^2.0.17
    bblanchon/ArduinoJson@^7.2.2
    mathieucarbou/ESPAsyncWebServer@^3.4.5
    madhephaestus/ESP32Servo @ ^3.2.1
    crankyoldgit/IRremoteESP8266 @ ^2.9.0

[env:esp32doit-devkit-v1]
upload_protocol = espota
upload_port = 192.168.100.235
upload_flags =
    --auth=${secrets.ota_password}
    --timeout=60

; Upload over USB serial (first flash / recovery)
[env:usb]
upload_speed = 921600